"""removes nullable=false in votable_id

Revision ID: 095314f54815
Revises: 4f5c4d139182
Create Date: 2025-05-02 13:34:00.150975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095314f54815'
down_revision = '4f5c4d139182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('votable_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('votable_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
