"""readds nullable

Revision ID: 1b39b38dac94
Revises: 095314f54815
Create Date: 2025-05-02 14:10:18.151516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b39b38dac94'
down_revision = '095314f54815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('votable_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('votable_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
