"""fresh start

Revision ID: 2b3b68607a30
Revises: 
Create Date: 2025-04-19 17:30:05.737112
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3b68607a30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        # Add 'title' column as nullable first
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('submitted_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_article_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_article_submitted_by_id_user'), 'user', ['submitted_by_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('content')
        batch_op.drop_column('user_id')

    # Populate the 'title' column with default values (e.g., empty string, 'Unknown', or based on other columns)
    op.execute("UPDATE article SET title = 'Default Title' WHERE title IS NULL")

    # Now, alter the 'title' column to be NOT NULL
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('title', nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_comment_article_id_article', type_='foreignkey')
        batch_op.drop_constraint('fk_comment_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_article_id_article'), 'article', ['article_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comment_user_id_user'), 'user', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fact_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=2000), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('fact_check', schema=None) as batch_op:
        batch_op.drop_column('content')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_article_id_article'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_user_id_user', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_comment_article_id_article', 'article', ['article_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('content', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_article_submitted_by_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_article_user_id_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('submitted_by_id')
        batch_op.drop_column('url')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
