"""removes username once more

Revision ID: 4b8725dcb298
Revises: f69250e8c418
Create Date: 2025-04-23 14:50:27.229538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8725dcb298'
down_revision = 'f69250e8c418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_username_user', type_='foreignkey')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_comment_username_user', 'user', ['username'], ['username'], ondelete='SET NULL')

    # ### end Alembic commands ###
