"""deletes required source field

Revision ID: 5aa189bbe8a9
Revises: 1b39b38dac94
Create Date: 2025-05-06 10:40:01.081073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa189bbe8a9'
down_revision = '1b39b38dac94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_check', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=150), nullable=False))

    # ### end Alembic commands ###
