"""changes fact_check logic to include predefined labels

Revision ID: d8b639b9a01e
Revises: 5a1b88cabaf3
Create Date: 2025-04-22 16:06:16.588885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b639b9a01e'
down_revision = '5a1b88cabaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fact_check_level', sa.Integer(), nullable=False, default='0'))
        batch_op.drop_column('verified_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_status', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('fact_check_level')

    # ### end Alembic commands ###
