"""adds username column to comments

Revision ID: f69250e8c418
Revises: d8b639b9a01e
Create Date: 2025-04-23 14:41:06.135756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69250e8c418'
down_revision = 'd8b639b9a01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_username_user'), 'user', ['username'], ['username'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_username_user'), type_='foreignkey')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
